export const GLOBAL_LOADER = 'GLOBAL_LOADER';
export const GLOBAL_LOADER_RES = 'GLOBAL_LOADER_RES';

export const DO_DASHBOARDDATA = 'DO_DASHBOARDDATA';
export const DO_DASHBOARDDATA_RES = 'DO_DASHBOARDDATA_RES';

export const DO_DASHBOARDCOURSEDATA = 'DO_DASHBOARDCOURSEDATA';
export const DO_DASHBOARDCOURSEDATA_RES = 'DO_DASHBOARDCOURSEDATA_RES';

export const DO_STATECOLLEGEDATA = 'DO_STATECOLLEGEDATA';
export const DO_STATECOLLEGEDATA_RES = 'DO_STATECOLLEGEDATA_RES';

